### ISSUE TITLE
Make `make train` start actual training

### ISSUE THREAD

**Issue by astaff** [neuromation/cookiecutter-neuro-project#265]
After `neuro project init`, issuing `make train` will print `Replace this placeholder with a training script execution` which is not an expected behavior. Upon further examination, `Makefile` actually has a suggested training script already baked in.

I suggest:
1. Make `TRAINING_COMMAND="bash -c 'cd $(PROJECT_PATH_ENV) && python -u $(CODE_DIR)/train.py 2>&1'"` a default. Note `2>&1` - this will redirect `stderr` to `stdout` which may be useful when troubleshooting error as you can see them in `neuro logs` (neuro logs captures only `stdout`). This also has an added benefit of seeing `tqdm` progress line by line in `neuro logs`, as `tqdm` uses `stderr`.
 2. Add a trivial `train.py` that simply has `print('Add your training script to project-name/train.py')` that will give the user an idea of what to do next.

**Comment by ayushkovskiy** [comment]
1. Few comments:
a. `2>&1` is redundant as `neuro logs` *does* include `stderr`. To check this, run `submit neuromation/base 'bash -c "ls non-existing-file"'`, which prints error message to `stderr`. 
b. no, neither `PYTHONUNBUFFERED=1` nor `2>&1` won't fix the problem with tqdm:
```
neuro submit -e PYTHONUNBUFFERED=1 image:python-tqdm 'python -c "from tqdm import tqdm; import time; [time.sleep(0.1) for x in tqdm(range(100))]" 2>&1'
```
I have played a lot with it, and it seems that to make tqdm work in neuro logs, we need to disable buffering on docker side, because locally stream reading works just fine:
```
$ python -c "from tqdm import tqdm; import time; [time.sleep(0.1) for x in tqdm(range(100))]" 2> file.txt & 
[1] 1244336
$ tail -f file.txt 
 80%|████████  | 80/100 [00:08<00:02,  9.95it/s]^C
```
tqdm problem discussion: https://github.com/neuromation/platform-client-python/issues/1199

2. Totally agree with adding a trivial `train.py`, will do

**Comment by astaff** [comment]
Agreed re `2>&1`.

I was able to make tqdm progress appear after adding `print()` inside the loop. It does, however, only works with `PYTHONUNBUFFERED=1`

**Comment by ayushkovskiy** [comment]
> It does, however, only works with PYTHONUNBUFFERED=1

Could you please share your setup with working tqdm with `PYTHONUNBUFFERED=1`? I could not get it working:
```
$ cat tqdm_test.py 
from tqdm import tqdm
import time
import sys
#for station in tqdm(range(10), file=sys.stdout):
for station in tqdm(range(1000), ):
    time.sleep(0.1)

$ n submit -n tqdm -e PYTHONUNBUFFERED=1 -v storage:tqdm:/srv:rw image:python-tqdm "python /srv/tqdm_test.py"
... <no tqdm output>
```
