### ISSUE TITLE
Exclude cache files while uploading files from `modules/`

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#93]
```
Copy 'file:///home/ay/github/temp/name-of-the-project/modules' => 'storage://artemyushkovskiy/name-of-the-project/modules'
'file:///home/ay/github/temp/name-of-the-project/modules' ...
'file:///home/ay/github/temp/name-of-the-project/modules/__pycache__' DONE
'file:///home/ay/github/temp/name-of-the-project/modules' DONE
```
`__pycache__` definitely should not be uploaded.

**Comment by mariyadavydova** [comment]
How does this file/folder appear?

**Comment by ayushkovskiy** [comment]
automatically by Python interpreter

**Comment by anayden** [comment]
How about we upload everything and then delete `__pycache__` via `neuro rm`?

**Comment by ayushkovskiy** [comment]
> How about we upload everything and then delete

For me now, it looks as a hack :/  Since we are not in a big hurry now, maybe we can do this better?

1. using glob (by default in `neuro cp`)
2. I think the git approach using `.gitignore` is more clean: `.neuroignore` and not hard to implement. With same syntax as .gitignore :wink:. Though, it should be implemented in neuro cli itself, and it's a lot of work. If you like the idea, I'll create an issue for platform-client.

**Comment by ayushkovskiy** [comment]
more files to be ignored:
```
E     Full diff:
E     - {'00_notebook_tutorial.ipynb', '.ipynb_checkpoints'}
E     + {'00_notebook_tutorial.ipynb'}
```

**Comment by ayushkovskiy** [comment]
Should be fixed in https://github.com/neuromation/platform-client-python/issues/1182.

Please don't forget to tweak tests after the funcitonality is implemented:
https://github.com/neuromation/cookiecutter-neuro-project/blob/ce0614b50503a84987fc749d7ff522ae5fd86d01/tests/e2e/configuration.py#L76

here, we should add `.neuroignore` file to the `modules/` and remove this hack with `PROJECT_HIDDEN_FILES`

**Comment by ayushkovskiy** [comment]
Note: AWS uses CLI options instead of a file, and I like it:
```
$ aws s3 help
...
      You can do
       this by providing an --exclude or --include  argument  multiple  times,
       e.g.   --include  "*.txt"  --include  "*.png".  When there are multiple
       filters, the rule is the filters that appear later in the command  take
       precedence  over filters that appear earlier in the command.  For exam-
       ple, if the filter parameters passed to the command were

          --exclude "*" --include "*.txt"
```

**Comment by ayushkovskiy** [comment]
Already implemented in neuro https://github.com/neuromation/platform-client-python/issues/1182
